/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
      colors: {
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container": "#1f1f1f",
        "surface-container-low": "#1b1b1b",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "surface-container-lowest": "#0e0e0e",
        "surface-variant": "#353535",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#e7bdb8",
        "background": "#131313",
        "on-background": "#e2e2e2",
        "primary": "#ffb4ac",
        "primary-container": "#e82127",
        "on-primary": "#690007",
        "on-primary-container": "#140000",
        "primary-fixed": "#ffdad6",
        "primary-fixed-dim": "#ffb4ac",
        "secondary": "#c8c6c8",
        "secondary-container": "#474649",
        "on-secondary": "#303032",
        "on-secondary-container": "#b6b4b7",
        "tertiary": "#8aceff",
        "tertiary-container": "#007eb5",
        "on-tertiary": "#00344e",
        "on-tertiary-container": "#ffffff",
        "outline": "#ae8884",
        "outline-variant": "#5d3f3c",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#303030",
        "inverse-primary": "#c00015",
        "surface-tint": "#ffb4ac",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
