services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: eyf-app:latest
    container_name: eyf-app
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
