/**
 * Mock Offer Letter — generates a realistic-feeling congratulations PDF
 * so the student knows what one looks like, and so it lives on their fridge
 * until the real one shows up. Phase 4 Week 32–34 per spec.
 */
import React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

const sty = StyleSheet.create({
  page: { padding: 56, fontFamily: "Helvetica", fontSize: 11, color: "#0A0A0A" },
  hdr: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 28 },
  company: { fontSize: 14, fontWeight: 700, letterSpacing: 1 },
  meta: { fontSize: 9, color: "#5A5A57" },
  title: { fontSize: 26, fontWeight: 700, marginTop: 16, marginBottom: 16 },
  body: { lineHeight: 1.6, marginBottom: 14, color: "#222" },
  table: { borderTopWidth: 1, borderTopColor: "#1C1C1C", borderTopStyle: "solid", marginTop: 14, paddingTop: 14 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: "#EEE", borderBottomStyle: "solid" },
  rowLabel: { color: "#5A5A57" },
  rowValue: { fontWeight: 700 },
  signOff: { marginTop: 28, color: "#222" },
  footer: { position: "absolute" as const, bottom: 40, left: 56, right: 56, fontSize: 8, color: "#8A8A87", textAlign: "center" as const },
});

export type OfferLetterInput = {
  candidateName: string;
  company: string;
  role: string;
  location: string;
  startDate: string;            // "10 July 2026"
  ctcInr: number;               // annual, in rupees
  joiningBonusInr?: number;
  esopValueInr?: number;
};

function fmtINR(n: number): string {
  if (n >= 10_000_000) return `₹${(n / 10_000_000).toFixed(2)} Cr`;
  if (n >= 100_000)    return `₹${(n / 100_000).toFixed(2)} L`;
  return `₹${n.toLocaleString("en-IN")}`;
}

function Doc({ data }: { data: OfferLetterInput }) {
  const today = new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" });
  return React.createElement(Document, null,
    React.createElement(Page, { size: "A4", style: sty.page },
      React.createElement(View, { style: sty.hdr },
        React.createElement(Text, { style: sty.company }, data.company.toUpperCase()),
        React.createElement(Text, { style: sty.meta }, today),
      ),
      React.createElement(Text, { style: sty.title }, "Letter of Offer"),
      React.createElement(Text, { style: sty.body }, `Dear ${data.candidateName},`),
      React.createElement(Text, { style: sty.body },
        `We're delighted to offer you the position of ${data.role} at ${data.company}, based in ${data.location}. ` +
        `This decision reflects the quality of your work, your interviews, and the impact we believe you'll have on our team.`),
      React.createElement(View, { style: sty.table },
        Row("Role", data.role),
        Row("Location", data.location),
        Row("Start date", data.startDate),
        Row("Annual CTC", fmtINR(data.ctcInr)),
        data.joiningBonusInr ? Row("Joining bonus", fmtINR(data.joiningBonusInr)) : null,
        data.esopValueInr   ? Row("ESOPs (4-year vest)", fmtINR(data.esopValueInr)) : null,
      ),
      React.createElement(Text, { style: { ...sty.body, marginTop: 20 } },
        "This is a mock offer letter generated by EYF to help you visualise the goal. " +
        "Tape it on your wall. The real one is coming."),
      React.createElement(Text, { style: sty.signOff },
        `Warm regards,\nThe ${data.company} hiring team`),
      React.createElement(Text, { style: sty.footer },
        `Generated by EYF · eyf.in · Not a binding offer of employment.`),
    ),
  );
}

function Row(label: string, value: string) {
  return React.createElement(View, { style: sty.row },
    React.createElement(Text, { style: sty.rowLabel }, label),
    React.createElement(Text, { style: sty.rowValue }, value),
  );
}

export async function renderOfferLetter(input: OfferLetterInput): Promise<Buffer> {
  return renderToBuffer(Doc({ data: input }));
}
